enum actionTypes {
  ADD_EXAMPLE = "EXAMPLE/ADD",
  REMOVE_EXAMPLE = "EXAMPLE/REMOVE",

  INC_COUNTER = "EXAMPLE/INC_COUNTER",
  DEC_COUNTER = "EXAMPLE/DEC_COUNTER",

  SET_STATE = "SET_STATE",
  SET_LOADING = "SET_LOADING"
}


export default actionTypes;